name: Logs Master

on:
  workflow_dispatch:

env:
  PM2_APP_ID: 3

jobs:
  get-logs:
    runs-on: self-hosted

    steps:
      - name: Logs pm2
        run: |
          pm2 logs $PM2_APP_ID --lines 1000
